//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gafel.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gafel.Domain.Resources.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email ou senha inválidos.
        /// </summary>
        public static string AUTH_INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("AUTH_INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário bloqueado. Tente novamente mais tarde.
        /// </summary>
        public static string AUTH_LOCKED_OUT {
            get {
                return ResourceManager.GetString("AUTH_LOCKED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login não permitido. Verifique se sua conta está confirmada.
        /// </summary>
        public static string AUTH_LOGIN_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("AUTH_LOGIN_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A requisição não possui token de autenticação..
        /// </summary>
        public static string AUTH_NO_TOKEN {
            get {
                return ResourceManager.GetString("AUTH_NO_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O token de autenticação está expirado.
        /// </summary>
        public static string AUTH_TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("AUTH_TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Token de autenticação inválido..
        /// </summary>
        public static string AUTH_TOKEN_INVALID {
            get {
                return ResourceManager.GetString("AUTH_TOKEN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Autenticação em dois fatores necessária.
        /// </summary>
        public static string AUTH_TWO_FACTOR_REQUIRED {
            get {
                return ResourceManager.GetString("AUTH_TWO_FACTOR_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF já cadastrado.
        /// </summary>
        public static string CPF_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("CPF_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF não pode ser vazio.
        /// </summary>
        public static string CPF_EMPTY {
            get {
                return ResourceManager.GetString("CPF_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF inválido.
        /// </summary>
        public static string CPF_INVALID {
            get {
                return ResourceManager.GetString("CPF_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CPF não pode ser atualizado.
        /// </summary>
        public static string CPF_UPDATE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("CPF_UPDATE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Um ou mais erros de validação ocorreram..
        /// </summary>
        public static string EXCEPTION_ERROR_ON_VALIDATION_DETAIL {
            get {
                return ResourceManager.GetString("EXCEPTION_ERROR_ON_VALIDATION_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro de validação.
        /// </summary>
        public static string EXCEPTION_ERROR_ON_VALIDATION_TITLE {
            get {
                return ResourceManager.GetString("EXCEPTION_ERROR_ON_VALIDATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha na autenticação.
        /// </summary>
        public static string EXCEPTION_INVALID_LOGIN_TITLE {
            get {
                return ResourceManager.GetString("EXCEPTION_INVALID_LOGIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário associado ao token não é mais válido.
        /// </summary>
        public static string EXCEPTION_INVALID_USER_TOKEN_DETAIL {
            get {
                return ResourceManager.GetString("EXCEPTION_INVALID_USER_TOKEN_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Perfil do usuário não foi encontrado.
        /// </summary>
        public static string EXCEPTION_PERSON_NOT_FOUND_DETAIL {
            get {
                return ResourceManager.GetString("EXCEPTION_PERSON_NOT_FOUND_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Perfil não encontrado.
        /// </summary>
        public static string EXCEPTION_PERSON_NOT_FOUND_TITLE {
            get {
                return ResourceManager.GetString("EXCEPTION_PERSON_NOT_FOUND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade inválida.
        /// </summary>
        public static string PERSON_CITY_INVALID {
            get {
                return ResourceManager.GetString("PERSON_CITY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de nascimento não pode ser no futuro.
        /// </summary>
        public static string PERSON_DATE_OF_BIRTH_FUTURE {
            get {
                return ResourceManager.GetString("PERSON_DATE_OF_BIRTH_FUTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de nascimento inválida.
        /// </summary>
        public static string PERSON_DATE_OF_BIRTH_INVALID {
            get {
                return ResourceManager.GetString("PERSON_DATE_OF_BIRTH_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de nascimento não pode ser atualizada.
        /// </summary>
        public static string PERSON_DATE_OF_BIRTH_UPDATE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("PERSON_DATE_OF_BIRTH_UPDATE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome não pode estar vazio.
        /// </summary>
        public static string PERSON_FULL_NAME_EMPTY {
            get {
                return ResourceManager.GetString("PERSON_FULL_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UF inválida.
        /// </summary>
        public static string PERSON_UF_INVALID {
            get {
                return ResourceManager.GetString("PERSON_UF_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não autorizado.
        /// </summary>
        public static string UNAUTHORIZED {
            get {
                return ResourceManager.GetString("UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro desconhecido.
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email já registrado.
        /// </summary>
        public static string USER_EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("USER_EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O email não pode estar vazio.
        /// </summary>
        public static string USER_EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("USER_EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O email é inválido.
        /// </summary>
        public static string USER_EMAIL_INVALID {
            get {
                return ResourceManager.GetString("USER_EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha não pode estar vazia.
        /// </summary>
        public static string USER_PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("USER_PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha atual incorreta.
        /// </summary>
        public static string USER_PASSWORD_INCORRECT {
            get {
                return ResourceManager.GetString("USER_PASSWORD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter pelo menos um número.
        /// </summary>
        public static string USER_PASSWORD_REQUIRES_NUMBER {
            get {
                return ResourceManager.GetString("USER_PASSWORD_REQUIRES_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter pelo menos um caractere especial.
        /// </summary>
        public static string USER_PASSWORD_REQUIRES_SPECIAL_CHAR {
            get {
                return ResourceManager.GetString("USER_PASSWORD_REQUIRES_SPECIAL_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve ter no mínimo 8 caracteres.
        /// </summary>
        public static string USER_PASSWORD_TOO_SHORT {
            get {
                return ResourceManager.GetString("USER_PASSWORD_TOO_SHORT", resourceCulture);
            }
        }
    }
}
