//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gafel.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gafel.Domain.Resources.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ou senha inválidos..
        /// </summary>
        public static string AUTH_CREDENTIALS_INVALID {
            get {
                return ResourceManager.GetString("AUTH_CREDENTIALS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login não permitido. Verifique se sua conta está confirmada..
        /// </summary>
        public static string AUTH_LOGIN_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("AUTH_LOGIN_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de autenticação está expirado..
        /// </summary>
        public static string AUTH_TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("AUTH_TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de autenticação inválido..
        /// </summary>
        public static string AUTH_TOKEN_INVALID {
            get {
                return ResourceManager.GetString("AUTH_TOKEN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A requisição não possui token de autenticação..
        /// </summary>
        public static string AUTH_TOKEN_REQUIRED {
            get {
                return ResourceManager.GetString("AUTH_TOKEN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticação em dois fatores é necessária..
        /// </summary>
        public static string AUTH_TWO_FACTOR_REQUIRED {
            get {
                return ResourceManager.GetString("AUTH_TWO_FACTOR_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário bloqueado. Tente novamente mais tarde..
        /// </summary>
        public static string AUTH_USER_LOCKED {
            get {
                return ResourceManager.GetString("AUTH_USER_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo inicial deve estar entre 0 e 10.000.000..
        /// </summary>
        public static string BANK_ACCOUNT_INITIAL_BALANCE_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("BANK_ACCOUNT_INITIAL_BALANCE_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome deve ter no máximo 100 caracteres..
        /// </summary>
        public static string BANK_ACCOUNT_NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("BANK_ACCOUNT_NAME_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar a conta bancária..
        /// </summary>
        public static string BANK_ACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("BANK_ACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ícone é obrigatório..
        /// </summary>
        public static string CATEGORY_ICON_REQUIRED {
            get {
                return ResourceManager.GetString("CATEGORY_ICON_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ícone deve ter no máximo 50 caracteres..
        /// </summary>
        public static string CATEGORY_ICON_TOO_LONG {
            get {
                return ResourceManager.GetString("CATEGORY_ICON_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome deve ter no máximo 100 caracteres..
        /// </summary>
        public static string CATEGORY_NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("CATEGORY_NAME_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar a categoria..
        /// </summary>
        public static string CATEGORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("CATEGORY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um ou mais erros de validação ocorreram..
        /// </summary>
        public static string EXCEPTION_ERROR_ON_VALIDATION_DETAIL {
            get {
                return ResourceManager.GetString("EXCEPTION_ERROR_ON_VALIDATION_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro de validação..
        /// </summary>
        public static string EXCEPTION_ERROR_ON_VALIDATION_TITLE {
            get {
                return ResourceManager.GetString("EXCEPTION_ERROR_ON_VALIDATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na autenticação..
        /// </summary>
        public static string EXCEPTION_INVALID_LOGIN_TITLE {
            get {
                return ResourceManager.GetString("EXCEPTION_INVALID_LOGIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário associado ao token não é mais válido..
        /// </summary>
        public static string EXCEPTION_INVALID_USER_TOKEN_DETAIL {
            get {
                return ResourceManager.GetString("EXCEPTION_INVALID_USER_TOKEN_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurso não encontrado..
        /// </summary>
        public static string EXCEPTION_NOT_FOUND_TITLE {
            get {
                return ResourceManager.GetString("EXCEPTION_NOT_FOUND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil do usuário não foi encontrado..
        /// </summary>
        public static string EXCEPTION_PERSON_NOT_FOUND_DETAIL {
            get {
                return ResourceManager.GetString("EXCEPTION_PERSON_NOT_FOUND_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil não encontrado..
        /// </summary>
        public static string EXCEPTION_PERSON_NOT_FOUND_TITLE {
            get {
                return ResourceManager.GetString("EXCEPTION_PERSON_NOT_FOUND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O identificador informado é inválido..
        /// </summary>
        public static string INVALID_IDENTIFIER {
            get {
                return ResourceManager.GetString("INVALID_IDENTIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome é obrigatório..
        /// </summary>
        public static string NAME_REQUIRED {
            get {
                return ResourceManager.GetString("NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit deve estar entre 1 e 100, inclusive.
        /// </summary>
        public static string PAGINATION_LIMIT_RANGE {
            get {
                return ResourceManager.GetString("PAGINATION_LIMIT_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit é obrigatório.
        /// </summary>
        public static string PAGINATION_LIMIT_REQUIRED {
            get {
                return ResourceManager.GetString("PAGINATION_LIMIT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset deve ser maior ou igual a 0.
        /// </summary>
        public static string PAGINATION_OFFSET_MIN_VALUE {
            get {
                return ResourceManager.GetString("PAGINATION_OFFSET_MIN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset é obrigatório.
        /// </summary>
        public static string PAGINATION_OFFSET_REQUIRED {
            get {
                return ResourceManager.GetString("PAGINATION_OFFSET_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade deve ter entre 3 e 60 caracteres..
        /// </summary>
        public static string PERSON_CITY_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("PERSON_CITY_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF já cadastrado..
        /// </summary>
        public static string PERSON_CPF_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("PERSON_CPF_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF não pode ser alterado..
        /// </summary>
        public static string PERSON_CPF_CHANGE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("PERSON_CPF_CHANGE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF inválido..
        /// </summary>
        public static string PERSON_CPF_INVALID {
            get {
                return ResourceManager.GetString("PERSON_CPF_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF é obrigatório..
        /// </summary>
        public static string PERSON_CPF_REQUIRED {
            get {
                return ResourceManager.GetString("PERSON_CPF_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento não pode ser alterada..
        /// </summary>
        public static string PERSON_DATE_OF_BIRTH_CHANGE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("PERSON_DATE_OF_BIRTH_CHANGE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento não pode ser no futuro..
        /// </summary>
        public static string PERSON_DATE_OF_BIRTH_IN_FUTURE {
            get {
                return ResourceManager.GetString("PERSON_DATE_OF_BIRTH_IN_FUTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ter no mínimo 18 anos..
        /// </summary>
        public static string PERSON_DATE_OF_BIRTH_MINIMUM_AGE {
            get {
                return ResourceManager.GetString("PERSON_DATE_OF_BIRTH_MINIMUM_AGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome completo é obrigatório..
        /// </summary>
        public static string PERSON_FULL_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("PERSON_FULL_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome completo deve ter no máximo 60 caracteres..
        /// </summary>
        public static string PERSON_FULL_NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("PERSON_FULL_NAME_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF inválida..
        /// </summary>
        public static string PERSON_UF_INVALID {
            get {
                return ResourceManager.GetString("PERSON_UF_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo inválido..
        /// </summary>
        public static string TYPE_INVALID {
            get {
                return ResourceManager.GetString("TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não autorizado..
        /// </summary>
        public static string UNAUTHORIZED {
            get {
                return ResourceManager.GetString("UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha atual incorreta..
        /// </summary>
        public static string USER_CURRENT_PASSWORD_INCORRECT {
            get {
                return ResourceManager.GetString("USER_CURRENT_PASSWORD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email já cadastrado..
        /// </summary>
        public static string USER_EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("USER_EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email inválido..
        /// </summary>
        public static string USER_EMAIL_INVALID {
            get {
                return ResourceManager.GetString("USER_EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email é obrigatório..
        /// </summary>
        public static string USER_EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("USER_EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha deve ter entre 8 e 60 caracteres..
        /// </summary>
        public static string USER_PASSWORD_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("USER_PASSWORD_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha é obrigatória..
        /// </summary>
        public static string USER_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("USER_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha deve conter pelo menos um número..
        /// </summary>
        public static string USER_PASSWORD_REQUIRES_NUMBER {
            get {
                return ResourceManager.GetString("USER_PASSWORD_REQUIRES_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha deve conter pelo menos um caractere especial..
        /// </summary>
        public static string USER_PASSWORD_REQUIRES_SPECIAL_CHAR {
            get {
                return ResourceManager.GetString("USER_PASSWORD_REQUIRES_SPECIAL_CHAR", resourceCulture);
            }
        }
    }
}
