import { FluentEmojiIcon } from '@fluentui-emoji/angular';
import {
  Automobile,
  Hamburger,
  House,
  ShoppingCart,
  Bank,
  Briefcase,
  MoneyBag,
  OfficeBuilding,
  BarChart,
  ChartIncreasing,
  ChartDecreasing,
  CreditCard,
  Receipt,
  ShoppingBags,
  HighVoltage,
  Droplet,
  FuelPump,
  DollarBanknote,
  Television,
  WorldMap,
  Airplane,
  Pill,
  RedHeart,
  GraduationCap,
  MusicalNotes,
  FilmProjector,
  OpenBook,
  Camera,
  BalanceScale,
  CardFileBox,
  Label,
  WrappedGift,
  Calendar,
  AlarmClock,
  WhiteQuestionMark,
  PawPrints,
  Laptop,
  Wrench,
  Toolbox,
  Bus,
  Train,
} from '@fluentui-emoji/angular/flat';

export const FLUENT_EMOJIS = {
  money: DollarBanknote,
  savings: MoneyBag,
  bank: Bank,
  creditCard: CreditCard,
  receipt: Receipt,
  chartUp: ChartIncreasing,
  chartDown: ChartDecreasing,
  investment: BarChart,
  balance: BalanceScale,
  work: Briefcase,
  office: OfficeBuilding,
  graduationCap: GraduationCap,
  book: OpenBook,
  laptop: Laptop,
  house: House,
  energy: HighVoltage,
  water: Droplet,
  fuel: FuelPump,
  tools: Wrench,
  toolbox: Toolbox,
  shoppingCart: ShoppingCart,
  shoppingBags: ShoppingBags,
  food: Hamburger,
  car: Automobile,
  bus: Bus,
  train: Train,
  airplane: Airplane,
  worldMap: WorldMap,
  tv: Television,
  movie: FilmProjector,
  music: MusicalNotes,
  camera: Camera,
  medicine: Pill,
  health: RedHeart,
  pets: PawPrints,
  gift: WrappedGift,
  calendar: Calendar,
  time: AlarmClock,
  documents: CardFileBox,
  label: Label,
  other: WhiteQuestionMark,
} as const satisfies Record<string, FluentEmojiIcon>;
